name: switchScript

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'switchScript.sh'
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

env:
  SCRIPT_SH: switchScript.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt install -y jq

    - name: "Build & Release"
      run: |
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
        chmod +x $SCRIPT_SH

        # Add retry logic here
        max_attempts=3
        attempt_num=1
        while [ $attempt_num -le $max_attempts ]; do
          echo "Attempt $attempt_num to run the script..."
          if ./$SCRIPT_SH; then
            echo "Script executed successfully on attempt $attempt_num."
            break
          else
            echo "Script failed on attempt $attempt_num."
            if [ $attempt_num -lt $max_attempts ]; then
              echo "Retrying in 10 seconds..." # Optional: add a delay
              sleep 10
            fi
            attempt_num=$((attempt_num+1))
          fi
        done

        # Check if the script ultimately failed after retries
        if [ $attempt_num -gt $max_attempts ]; then
          echo "Script failed after $max_attempts attempts."
          exit 1 # Exit with a non-zero status to indicate failure
        fi

        zip -rq SwitchSD.zip SwitchSD

    - name: Read description.txt
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./description.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ❤️ | 大气层个人整合包
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: main
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "${{ steps.description.outputs.content }}"
        artifacts: "SwitchSD.zip"

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

